name: Node CI

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node-version: ['12', '14', '16']
    env:
      OS: ${{ matrix.os }}
      NODE_VERSION: ${{ matrix.node-version }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, and test
      run: npm install && npm test && npm run coverage
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        files: ./coverage/lcov.info
        directory: ./coverage/
        flags: unittests
        env_vars: OS,NODE_VERSION
